[project]
name = "fastknock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.22"
dependencies = [
    "cobra==0.29.1",
    "cplex>=22.1.2.0",
    "docplex>=2.29.245",
    "scipy>=1.13.1",
]
